### ISSUE TITLE
<pubDate> not working, <lastBuildDate> works

### ISSUE THREAD

**Issue by eBornstein** [fabarea/rss_display#10]
I have 2 Problems:
1) I have installed tx_news (2.3.1 - TYPO3 6.0) and am trying to get the News with rss_display (3.0.1) on another website (TYPO3 7.6.2). 
If I use the tx_news standard <pubDate>, an old news shows. I cant figure out why. 
If I use <lastBuildDate> the correct news is showing.

2) I can't use my own Template. 
I have copied the Show.html in fileadmin, corrected the path in TS and changed the template in the plugin. 
Am I doing something wrong or did i forget something?
plugin.tx_rssdisplay {
        settings {
                templates {
                        # foo1 is just a key which must be unique
                        foo_1 {
                                label = My Template
                                path = fileadmin/templates/domain/Show.html
                        }
                }
        }
}

thx for helping ^^

**Comment by fabarea** [comment]
In the Template module  (TypoScript object browser) do you effectively see your changes?

**Comment by eBornstein** [comment]
I'm sorry. The problem with the template was probably the cache. Now that I have cleared the general cache it works. The new caching system is very chaotic.
But the problem with the <pubDate> can thus not solve.

**Comment by eBornstein** [comment]
And the first problem? Its not a Bug? Then it should be a hint in the documetation, that pubDate not supportet.
