### ISSUE TITLE
Editing right

### ISSUE THREAD

**Issue by erthi16** [fabarea/rss_display#13]
Can you tell me what right settings I have to give so non-administrors can change the plugin settings like number of items and feed URL?
For now only users with administrative rights can!

Thanks a million times!

Eric Thibault

**Comment by fabarea** [comment]
This is in the ACL, in the be_groups or be_users depending where you configure your BE users. They need to access the flexform settings (don't know by heart the field label in the BE, field name in the DB is pi_flexform)

**Comment by erthi16** [comment]
Yes I've found the setting... I have to give rights to insert plugins in pages... I would have prefered to pinpoint your specific plugin and idealy what settings can be changed... maybe in a futur release? ;)

Thank you for your help!

Eric Thibault
