### ISSUE TITLE
Change cache configuration to only override the minimum

### ISSUE THREAD

**Issue by sypets** [fabarea/rss_display#19]
If the cache configuration is changed as recommended in the core api (https://docs.typo3.org/typo3cms/CoreApiReference/ApiOverview/CachingFramework/Configuration/Index.html#cache-configurations), it would be possible to set a different backend in LocalConfiguration.php / AddidtionalConfiguration.php. Currently the backend always defaults to the DatabaseBackend. I am not aware of any way to change the defaults. If you change the cache backend for rssdisplay in LocalConfiguration.php this will get overridden by  rssdisplay/ext_localconf.php.

What I mean is change this:

```
$TYPO3_CONF_VARS['SYS']['caching']['cacheConfigurations']['rssdisplay'] = [
    'frontend' => 'TYPO3\CMS\Core\Cache\Frontend\StringFrontend',
//	'options' => array(),
    'groups' => ['all', 'rssdisplay']
];
```

to somthing like  this:

```
$TYPO3_CONF_VARS['SYS']['caching']['cacheConfigurations']['rssdisplay']['frontend'] = \TYPO3\CMS\Core\Cache\Frontend\StringFrontend::class;
$TYPO3_CONF_VARS['SYS']['caching']['cacheConfigurations']['rssdisplay']['groups'] = array('all', 'rssdisplay');
```

I can create a pull request.

**Comment by fabarea** [comment]
Yes, please. Would be helpful.
