### ISSUE TITLE
Update SimplePie to version 1.5 solved my problem with double-encoded umlauts

### ISSUE THREAD

**Issue by schmidi2** [fabarea/rss_display#24]
The TYPO3 extension rss_display current version 4.0.0 and still uses the old version 1.4-dev of the SimplePie.

As I had problems displaying rss items with german umlauts (like äöüÄÖÜ), they seem to be html-encoded two times, updating the SimplePie library to newest version 1.5 solved the problem.

Simply download the newest version of SimplePie from http://simplepie.org/downloads/, unzip and upload (and overwrite) the content of simplepie-1.5/library/ to your TYPO3 installation into typo3conf/ext/rss_display/Resources/Private/PHP/ . Nothing more todo (I am using TYPO3 8.7).

Please update SimplePie directly in the extension.

**Comment by adrienjacob** [comment]
Thanks for the tip, solved a similar problem (on asian languages)... I just submitted a pull request accordingly.

**Comment by fabarea** [comment]
Resolves via #25

**Comment by adrienjacob** [comment]
thanks !
