### ISSUE TITLE
Multiple instances of plugin on same page

### ISSUE THREAD

**Issue by stephan-tittel** [fabarea/rss_display#35]
Adding 2 rss_display instances with different feed rendering templates (from typo3conf/ext/rss_display/Resources/Private/Templates/Feed/) on the same page does not work. Both instances will render with the same template, so one of the instances does not use the configured template.

`Typo3: 9.5.4 / rss_display: 4.2.1`

**Comment by fabarea** [comment]
Ack. It needs to be debugged here. PR welcome.

**Comment by stephan-tittel** [comment]
It's a bug in the calculation of the cache identifier. The following works for me, but isn't completely correct either.
```diff
diff --git a/Classes/Controller/FeedController.php b/Classes/Controller/FeedController.php
index 30292cd..777cf95 100644
--- a/Classes/Controller/FeedController.php
+++ b/Classes/Controller/FeedController.php
@@ -134,7 +134,7 @@ class FeedController extends ActionController
      
     protected function getCacheIdentifier()
     {
-        return md5($this->settings['feedUrl']);
+        return md5($this->settings['feedUrl'] . $this->settings['template'] . $this->settings['numberOfItems']);
     }
```

**Comment by fabarea** [comment]
4.2.2 on his way to the TER

**Comment by stephan-tittel** [comment]
Perfect, thanks!
