### ISSUE TITLE
php 7.4 compatibility (SimplePie to 1.5.5)

### ISSUE THREAD

**Issue by osahner** [fabarea/rss_display#48]
Upgrading SimplePie to 1.5.5 helped.

but the UpdateScript bails out with:
`Call to a member function exec_SELECTgetRows() on null | Error thrown in file typo3temp/var/transient/ext_update21985a820dab12624abf6ea84e5480d6.php in line 33.`

```php
        public function updateNewIdentity() {

                $condition = "list_type='rss_display_pi1'";
                $rows = $this->getDatabaseConnection()->exec_SELECTgetRows('*', 'tt_content', $condition);
```

**Comment by fabarea** [comment]
I just released a new version which does not contain the UpdateScript.
