### ISSUE TITLE
php 7.4: SimplePie\Parse\Date.php raise PHP runtime deprecation notice about implode() arguments

### ISSUE THREAD

**Issue by UmbrellaDish** [fabarea/rss_display#53]
```
PHP Runtime Deprecation Notice: implode(): Passing glue string after array is deprecated. Swap the parameters in .../typo3conf/ext/rss_display/Resources/Private/PHP/SimplePie/SimplePie/Parse/Date.php line 557
```

Cited from Typo3 9.5.21 with rss_display 4.4.0 which incorporates SimplePie. I verified that the error still exists in current master branch of SimplePie repository. EDIT: Why I post this issue here instead of at SimplePie's repo, you might wonder? Because it is directly incorporated instead here of only a dependency, I was not sure whom to address.

**Comment by robertvonhackwitz** [comment]
It would be enough to upgrade SimplePie to 5.1.6 version

**Comment by emmguyot** [comment]
I had the same problem and I've upgraded to SimplePie 1.5.6 and it works.
You can download SImplePie from here https://github.com/simplepie/simplepie/releases/tag/1.5.6

**Comment by fzuerker** [comment]
Pushing this issue.
Could the included SimplePie Version be updated or better yet - be handled as Composer dependency like it's done in @cjanody pull request?
