### ISSUE TITLE
Error messages after saving the content elemen

### ISSUE THREAD

**Issue by newsdesigner** [fabarea/rss_display#57]
The extension generates an error in the log that occurs quite often.

> Core: Error handler (FE): PHP Runtime Deprecation Notice: implode(): Passing glue string after array is deprecated. Swap the parameters in /path/typo3conf/ext/rss_display/Resources/Private/PHP/SimplePie/SimplePie/Parse/Date.php line 558

In addition, an error message is always output when saving:

> 1: Attempt to modify record '[Kein Titel]' (tt_content:29) without permission. Or non-existing page.

Moving the templates to another location does not work correctly either.

**Comment by jmverges** [comment]
diff --git a/Classes/Backend/TceForms.php b/Classes/Backend/TceForms.php
index 8a08184..34343b2 100644
--- a/Classes/Backend/TceForms.php
+++ b/Classes/Backend/TceForms.php
@@ -54,7 +54,7 @@ class TceForms extends AbstractFormElement
                 );
             }
 
-            $output = sprintf('<select name="data[tt_content][%s][pi_flexform][data][sDEF][lDEF][settings.template][vDEF]">%s</select>',
+            $output = sprintf('<select data-formengine-input-name="data[tt_content][%s][pi_flexform][data][sDEF][lDEF][settings.template][vDEF]">%s</select>',
                 $params['row']['uid'],
                 implode("\n", $options)
             );

**Comment by sypets** [comment]
Get same error message as above. 

@jmverges If you already have a fix that works, can you create a PR from it?

(I don't know what this does, it looks hacky, either way).

**Comment by sypets** [comment]
Instead of this:

```
<settings.template>
  <TCEforms>
<label>LLL:EXT:rss_display/Resources/Private/Language/locallang.xlf:tt_content.tx_rssdisplay_template</label>
      <config>
      <type>user</type>
    <renderType>rssDisplayFeedTemplate</renderType>
  </config>
</TCEforms>
</settings.template>

```

It might be possible to use [itemsProcFunc](https://docs.typo3.org/m/typo3/reference-coreapi/10.4/en-us/ApiOverview/FlexForms/Index.html#populate-a-select-field-with-a-php-function-itemsprocfunc)
