### ISSUE TITLE
 Attempt to modify record '[No title]' (tt_content:xxxxxx) without permission. Or non-existing page.

### ISSUE THREAD

**Issue by humanook** [fabarea/rss_display#64]
When I create an new content element in TYPO3 10.4.14 , I get the following error

"Attempt to modify record '[No title]' (tt_content:xxxxxx) without permission. Or non-existing page."

xxxxxx is not found. because xxxxxx is not content uid for new content element.

**Comment by plojewski** [comment]
@fabarea Could you please publish the fix to ter please https://extensions.typo3.org/extension/rss_display ?
