### ISSUE TITLE
I cannot activate the extension in TYPO3 v10.4 in composer mode

### ISSUE THREAD

**Issue by someplace53** [fabarea/rss_display#75]
If I do `composer req fab/rss-display` and then try to activate it through the ExtensionManger, I get the following error message (debug mode):
> (1/1) #1519931815 UnexpectedValueException
> The package "rss_display" depends on "simplepie/simplepie" which is not present in the system.

As I still need to activate the extension in TYPO3 v10.4, the newest version of this extension seems not to work with TYPO3 version 10.4. My suspicion is that this is a problem with TYPO3 rather than this extension, but you could remove 10.4 version constraint (I did not test this with 11.5)

Tested in TYPO3 Version 10.4.31.

btw as a workaround you could install a lower version (5.1) and than update the extension and this seems to work quite fine, with the exception that you cannot activate or deactivate any extension anymore

**Comment by someplace53** [comment]
small addition on my part, it seems to work if you add the `constraints` part from the last version to the `ext_emconf.php`:
```php
<?php

$EM_CONF[$_EXTKEY] = [
    'title' => 'RSS Feed Display',
    'description' => 'Fetch a RSS / Atom Feed and display its content on the Frontend.',
    'category' => 'plugin',
    'version' => '6.0.0',
    'state' => 'stable',
    'author' => 'Fabien Udriot',
    'author_email' => 'fabien@ecodev.ch',
    'author_company' => 'Ecodev',
    'constraints' => [
        'depends' => [
            'typo3' => '9.5.0-11.5.99',
        ],
        'conflicts' => [
        ],
        'suggests' => [
        ],
    ],
];
```
and yes I increased the version number for the constraint.

**Comment by mbrodala** [comment]
This is exactly the correct fix. Without `constraints/depends` the TYPO3 package manager will fall back to `require` from the `composer.json` of a package. Which in this case leads to the mentioned error.
